import type { Service, AreaPage, Review } from '@/types'

export const services: Service[] = [
  {
    slug: 'new-construction',
    title: 'New Construction Plumbing',
    description: 'We handle all phases of plumbing for new builds. Systems are code-compliant and built to last. We work with contractors and architects on custom homes and commercial developments.',
    image: '/images/service-new-construction-plumbing.webp',
    features: ['Rough-in plumbing', 'Underground water lines', 'Gas line installation', 'Fixture installation', 'Drain and vent systems', 'System planning', 'Material selection'],
    faqs: [
      { question: 'Do you provide plumbing design for custom home builds?', answer: 'Yes. We design layouts around your home\'s architecture and how you use each room. We focus on water efficiency, good pressure, and easy access.' },
      { question: 'Can you handle plumbing for multi-unit residential buildings?', answer: 'Yes. We install systems for duplexes, townhomes, and apartments with shared water and sewer. We handle complex layouts and meter setups.' },
      { question: 'Will my new plumbing system meet state codes?', answer: 'Yes. Everything we install meets current Idaho plumbing codes. Your property will be ready for city or county inspection.' },
      { question: 'Do you offer water-saving plumbing options for new homes?', answer: 'Yes. We install low-flow toilets, efficient showerheads, and smart water heaters. These save water and lower your utility bills.' },
      { question: 'How early should plumbing start during new construction?', answer: 'Plumbing starts during the rough-in phase, right after framing and before insulation. We coordinate with your builder to time it right.' },
      { question: 'Do you install tankless water heaters during construction?', answer: 'Yes. We install tankless systems during the build with proper venting and hookups. They save space and give you hot water on demand.' },
      { question: 'How do you handle inspections for new construction plumbing?', answer: 'We schedule all required inspections and stay on-site to answer questions. Our work is code-compliant from the start.' },
      { question: 'Can your plumbing work accommodate future renovations?', answer: 'Yes. We design with future access points and flexible layouts. That way, upgrades down the road are easier and cheaper.' },
    ],
    relatedServices: ['radiant-heat', 'water-heaters', 'septic-systems'],
  },
  {
    slug: 'commercial',
    title: 'Commercial Plumbing',
    description: 'We handle plumbing for retail, industrial, and office properties. High-demand systems built to code and built to last. We manage every stage, from new builds to renovations.',
    image: '/images/service-commercial-plumbing-project.webp',
    features: ['Tenant improvements', 'Grease trap installation', 'Backflow prevention', 'Commercial water heaters', 'ADA-compliant fixtures', 'High-demand system design'],
    faqs: [
      { question: 'What types of commercial buildings do you service?', answer: 'Office buildings, restaurants, warehouses, medical centers, retail stores, schools, and mixed-use developments. Each gets a system built for its specific needs.' },
      { question: 'Do you handle plumbing for new commercial builds?', answer: 'Yes. We do full commercial systems for new construction. We coordinate with builders to hit code and keep the project on schedule.' },
      { question: 'Are your commercial plumbing systems energy efficient?', answer: 'Yes. We use high-efficiency water heaters, low-flow fixtures, and smart layouts to cut water use and operating costs.' },
      { question: 'Can you install ADA-compliant plumbing fixtures?', answer: 'Yes. We install ADA-compliant sinks and toilets that meet all clearance and height requirements. Your property will be fully accessible.' },
      { question: 'How soon can you start on a commercial project?', answer: 'It depends on the scope. We give you a clear timeline and start as soon as permits and plans are finalized.' },
      { question: 'What areas around Spirit Lake do you cover?', answer: 'We serve commercial clients in Spirit Lake, Athol, Rathdrum, Blanchard, and Sandpoint. Also rural areas in Kootenai and Bonner Counties.' },
      { question: 'Do you offer emergency repair services?', answer: 'Yes. For burst pipes or major system failures, we do urgent commercial repairs. We focus on minimizing downtime and protecting your property.' },
      { question: 'Is regular maintenance offered for commercial properties?', answer: 'Yes. We offer inspections, system flushing, and preventative maintenance. Routine service cuts down on emergencies and keeps things running.' },
    ],
    relatedServices: ['new-construction', 'sewer-line', 'water-heaters'],
  },
  {
    slug: 'radiant-heat',
    title: 'Radiant Heat & In-Floor Systems',
    description: 'Stay warm through Idaho\'s winters with radiant heating. We install and maintain in-floor systems that heat evenly and save energy. We design custom layouts for your home.',
    image: '/images/service-radiant-heat-boiler.webp',
    features: ['In-floor radiant heating', 'Boiler installation and repair', 'Hydronic heating systems', 'Thermostat and zone control', 'System flushing and maintenance', 'Custom heating layouts'],
    faqs: [
      { question: 'Is radiant heat suitable for older homes in Spirit Lake?', answer: 'Yes. Modern retrofitting lets us add radiant heat to older homes without tearing up the whole floor. We work with what you have.' },
      { question: 'Can radiant floor heating be used with carpet?', answer: 'Yes, but tile and hardwood transfer heat better. We can make it work under carpet with the right insulation and padding.' },
      { question: 'How long does radiant heating last?', answer: 'Usually 25 to 35 years. Hydronic systems use durable tubing that holds up well. With basic maintenance, they run for decades.' },
      { question: 'Will radiant heat increase my energy bills?', answer: 'No. Radiant heating often lowers costs. It heats surfaces directly at lower temperatures and doesn\'t waste energy cycling on and off.' },
      { question: 'Is radiant heat safe for families with children or pets?', answer: 'Yes. The system is hidden with no hot surfaces or exposed parts. No vents, no dust, no sharp edges.' },
      { question: 'Can I control different areas of the house separately?', answer: 'Yes. We divide the system into zones with their own thermostats. You heat only the rooms you use.' },
      { question: 'How long does installation take?', answer: 'For new construction, a few days along with the build schedule. Retrofitting existing floors takes 2 to 5 days depending on the room.' },
      { question: 'What type of boiler is best for radiant heating in Idaho?', answer: 'High-efficiency condensing boilers work best. We match the boiler size to your home\'s square footage and climate.' },
    ],
    relatedServices: ['new-construction', 'water-heaters', 'remodels'],
  },
  {
    slug: 'water-heaters',
    title: 'Water Heater Installation & Replacement',
    description: 'We install and repair tank and tankless water heaters. We help you pick the right model for your family size, usage, and budget.',
    image: '/images/service-water-heater-installation.webp',
    features: ['Tank water heaters (gas and electric)', 'Tankless water heaters', 'Hybrid and heat pump models', 'Water heater repair', 'Annual maintenance', 'Energy-efficient recommendations'],
    faqs: [
      { question: 'How long does a water heater typically last in Idaho?', answer: 'Tank models last 8 to 12 years. Tankless can go 20 years with proper maintenance. Hard water in North Idaho means regular flushing helps.' },
      { question: 'What size water heater do I need for my home?', answer: 'It depends on household size and water use. A family of four usually needs a 50-gallon tank. We help you pick without overspending.' },
      { question: 'Are tankless water heaters suitable for colder climates like Spirit Lake?', answer: 'Yes. Properly sized and installed with freeze protection, they handle Idaho winters well. They\'re efficient and give you hot water on demand.' },
      { question: 'Why is my water heater making rumbling noises?', answer: 'Sediment buildup at the bottom of the tank. Annual flushing prevents damage and keeps it running efficiently.' },
      { question: 'What are the signs that my water heater needs repair or replacement?', answer: 'Rusty water, inconsistent heat, odd noises, leaks, or higher energy bills. If it\'s over 10 years old, replacement is often the better call.' },
      { question: 'Can I install a water heater myself?', answer: 'You can, but we don\'t recommend it. Professional installation means code compliance, safety, and a valid warranty.' },
      { question: 'How can I reduce energy costs related to my water heater?', answer: 'Insulate the tank, set the thermostat to 120 degrees, and consider upgrading to a tankless model. Low-flow fixtures help too.' },
      { question: 'Do I need a permit to replace a water heater in Idaho?', answer: 'Yes, most towns require a plumbing permit. We handle that for you.' },
    ],
    relatedServices: ['water-softeners', 'remodels', 'new-construction'],
  },
  {
    slug: 'water-softeners',
    title: 'Water Softeners',
    description: 'We install and service water softeners for cleaner water and longer-lasting fixtures. Hard water causes scale, stains, and buildup. Our systems improve taste and cut soap usage.',
    image: '/images/service-water-softener-installation.webp',
    features: ['Water softener installation', 'Water filtration systems', 'Iron and sulfur removal', 'Reverse osmosis systems', 'System maintenance', 'Water quality testing'],
    faqs: [
      { question: 'How do I know if I need a water softener?', answer: 'Scale on fixtures, soap that won\'t lather, or stiff laundry after washing. A water test confirms calcium and magnesium levels.' },
      { question: 'Is hard water harmful to my plumbing system?', answer: 'Yes. Scale builds up inside pipes and water heaters, restricting flow and shortening their life. Addressing it early saves money.' },
      { question: 'What\'s the difference between salt-based and salt-free softeners?', answer: 'Salt-based systems remove hardness minerals through ion exchange. Salt-free systems change the mineral structure so scale doesn\'t form. Salt-free is lower maintenance but works best with moderate hardness.' },
      { question: 'How often does a softener need maintenance?', answer: 'Keep the salt reservoir filled and clean the brine tank. A professional check once a year catches issues early.' },
      { question: 'Will a water softener make my water safe to drink?', answer: 'No. It only removes calcium and magnesium. For drinking water, pair it with a reverse osmosis system.' },
      { question: 'How long does a typical water softener last?', answer: '10 to 15 years with proper maintenance. Water quality and usage affect how long it holds up.' },
      { question: 'Can I install a softener in a home with well water?', answer: 'Yes. Well water often needs pre-filtration for iron or sediment. We test the water and set up a system that handles it all.' },
      { question: 'Do water softeners increase water usage?', answer: 'Older models use water during regeneration. Modern units regenerate only when needed, which cuts waste way down.' },
    ],
    relatedServices: ['water-heaters', 'new-construction'],
  },
  {
    slug: 'toilets-faucets',
    title: 'Toilets & Faucets',
    description: 'We install and repair toilets and faucets. Low-flow upgrades, leak repairs, and commercial-grade fixtures. We aim to cut water waste and stop problems before they start.',
    image: '/images/service-toilets-faucets-plumbing.webp',
    features: ['Toilet installation and repair', 'Faucet installation and repair', 'Low-flow fixture upgrades', 'Commercial-grade fixtures', 'Leak detection and repair'],
    faqs: [
      { question: 'How do I know if my faucet needs replacing instead of repairing?', answer: 'If it keeps leaking after repairs or shows rust, replacement is usually more cost-effective. Newer models also use less water.' },
      { question: 'What\'s causing my toilet to run constantly?', answer: 'Usually a worn flapper, a bad fill valve, or sediment. These parts are easy to replace and stop the water waste.' },
      { question: 'Can I upgrade to water-saving fixtures in an older home?', answer: 'Yes. Low-flow toilets and aerated faucets work with older plumbing when installed correctly. We handle the fit and code compliance.' },
      { question: 'Why is my faucet making a hammering or squealing noise?', answer: 'Water hammer, worn washers, or pressure issues. We find the source and fix it before it causes pipe damage.' },
      { question: 'How long does a toilet installation take?', answer: '1 to 2 hours for a standard install. Corroded flanges or pipe adjustments can add time, but most are done same day.' },
      { question: 'Is it normal for faucet handles to become stiff or hard to turn?', answer: 'No. That usually means mineral buildup or worn parts. We can clean or replace the components to get it moving smoothly.' },
      { question: 'Are there any rebates for installing water-saving fixtures in Idaho?', answer: 'Yes. Many Idaho utilities offer rebates for WaterSense-certified fixtures. We can help you find and apply for them.' },
      { question: 'Do I need a plumber to install a faucet I bought myself?', answer: 'Not required, but DIY installs can cause leaks and water damage. We make sure connections are tight and code-compliant.' },
    ],
    relatedServices: ['bathtubs-showers', 'remodels'],
  },
  {
    slug: 'bathtubs-showers',
    title: 'Bathtubs & Showers',
    description: 'We install bathtubs and showers that work well and look good. Walk-in tubs, tiled showers, and custom designs. We focus on water pressure, comfort, and durability.',
    image: '/images/service-bathtubs-showers-plumbing.webp',
    features: ['Tub installation and replacement', 'Shower pan installation', 'Tile-ready shower bases', 'Jacuzzi and soaking tubs', 'ADA-compliant showers', 'Custom shower systems'],
    faqs: [
      { question: 'How long does it take to install a new bathtub or shower?', answer: 'Most take 1 to 3 days. We plan each step ahead to minimize disruption.' },
      { question: 'Can I convert my tub into a shower without redoing the entire bathroom?', answer: 'Yes. We modify the plumbing and use materials that match your existing finishes. No full remodel needed.' },
      { question: 'Do I need permits for bathtub or shower installations in Spirit Lake?', answer: 'In most cases, yes. We handle the permits and make sure everything passes inspection.' },
      { question: 'What materials do you recommend for shower walls?', answer: 'Ceramic tile, acrylic panels, or natural stone. They\'re durable, resist mold, and are easy to clean.' },
      { question: 'How can I prevent mold and mildew in my shower?', answer: 'Good ventilation and routine cleaning. We also use waterproof sealants during installation to keep moisture out.' },
      { question: 'Are walk-in tubs a good choice for seniors?', answer: 'Yes. They have built-in seating, grab bars, and non-slip surfaces. Great for aging in place safely.' },
      { question: 'Will hard water affect my shower fixtures?', answer: 'Yes. Mineral deposits build up over time. Scale-resistant fixtures help, and a water softener protects the whole system.' },
      { question: 'Can you replace my shower without replacing the plumbing?', answer: 'If the existing pipes are in good shape and up to code, yes. We only update what needs updating.' },
    ],
    relatedServices: ['toilets-faucets', 'remodels'],
  },
  {
    slug: 'dishwashers',
    title: 'Dishwashers & Disposals',
    description: 'We install dishwashers and garbage disposals the right way. Leak-free connections, proper venting, and compatibility with all major brands.',
    image: '/images/service-dishwasher-disposal-install.webp',
    features: ['Dishwasher installation', 'Garbage disposal installation', 'Drain line connection', 'Leak repair', 'Appliance hookup', 'Ventilation setup'],
    faqs: [
      { question: 'How long does it take to install a dishwasher or garbage disposal?', answer: '1 to 2 hours if existing connections are in place. Complex setups take a bit longer.' },
      { question: 'Can I replace a dishwasher myself, or should I hire a plumber?', answer: 'You can do it yourself, but incorrect hookups cause leaks and void warranties. We do it right the first time.' },
      { question: 'What causes a garbage disposal to jam or stop working?', answer: 'Fibrous foods, bones, grease, or foreign objects. We clear the jam and check for damage.' },
      { question: 'Why does my dishwasher smell bad or not drain properly?', answer: 'Clogged filters or blocked drain lines. We clear the obstruction and make sure the drainage is set up correctly.' },
      { question: 'Will hard water affect my dishwasher or disposal performance?', answer: 'Yes. Scale builds up in spray arms, valves, and motors. A water softener helps protect your appliances.' },
      { question: 'Do I need a new air gap with a dishwasher installation?', answer: 'Usually yes. It keeps dirty water from backing into the dishwasher. We install or connect one as needed.' },
      { question: 'Can I install a disposal under any kitchen sink?', answer: 'Most sinks work, but we check for space, support, and electrical access first.' },
      { question: 'What are the signs I need a new dishwasher or disposal?', answer: 'Leaks, poor drainage, bad smells, loud operation, or frequent repairs. We help you decide if replacing is worth it.' },
    ],
    relatedServices: ['remodels', 'toilets-faucets'],
  },
  {
    slug: 'sewer-line',
    title: 'Sewer Line Replacement',
    description: 'We replace damaged or outdated sewer lines using camera inspections and trenchless methods when possible. Minimal digging, maximum reliability.',
    image: '/images/service-sewer-line-replacement.webp',
    features: ['Sewer line inspection', 'Trenchless sewer repair', 'Sewer line replacement', 'Pipe bursting', 'Drain cleaning', 'Camera inspection'],
    faqs: [
      { question: 'How do I know if I need a sewer line replacement?', answer: 'Persistent clogs, bad smells, wet yard spots, or backups in multiple drains. A camera inspection tells us for sure.' },
      { question: 'What\'s the difference between repair and replacement?', answer: 'Repair fixes a specific damaged spot. Replacement takes out the whole line. Severe or widespread damage calls for replacement.' },
      { question: 'How long does sewer line replacement take?', answer: 'Most residential jobs are done in 1 to 3 days. It depends on soil, pipe length, and the method we use.' },
      { question: 'Will my yard be destroyed during replacement?', answer: 'Not with trenchless options. Even with traditional methods, we work to preserve your landscaping.' },
      { question: 'Is trenchless sewer replacement available?', answer: 'Yes, for many properties. We assess depth, pipe condition, and soil to see if it\'s a good fit.' },
      { question: 'Does Preferred Plumbing Solutions handle permits?', answer: 'Yes. We take care of all permits and inspections so you don\'t have to deal with the paperwork.' },
      { question: 'What types of pipe materials do you use?', answer: 'PVC and HDPE. They resist corrosion, root intrusion, and ground movement.' },
      { question: 'Is sewer line replacement covered by homeowners insurance?', answer: 'It depends on your policy and the cause. We help document the issue for claims, but check with your provider.' },
    ],
    relatedServices: ['septic-systems', 'emergency'],
  },
  {
    slug: 'septic-systems',
    title: 'Septic Systems',
    description: 'We design, install, and maintain septic systems for Idaho soil and water conditions. Soil testing, tank installation, drain fields, and routine pumping.',
    image: '/images/service-septic-system-installation.webp',
    features: ['Septic system design', 'New septic installation', 'Septic tank pumping', 'Drain field repair', 'System inspections', 'Soil testing'],
    faqs: [
      { question: 'How often should I pump my septic tank?', answer: 'Every 3 to 5 years, depending on household size and usage. Skipping it can damage your drain field.' },
      { question: 'What are the signs my septic system needs service?', answer: 'Slow drains, gurgling pipes, wet spots in the yard, or sewage odors. Don\'t wait once you notice these.' },
      { question: 'Can I install a septic system myself?', answer: 'Idaho requires licensed pros for septic design and installation. DIY installs often fail inspection.' },
      { question: 'Is it safe to use additives in my septic tank?', answer: 'Most systems don\'t need them. Some additives can harm the bacteria your tank relies on.' },
      { question: 'How long does a septic system last?', answer: '20 to 40 years with proper maintenance. Regular pumping and inspections make a big difference.' },
      { question: 'What permits are required for a new septic system?', answer: 'A site evaluation and permit from Panhandle Health District are needed before installation.' },
      { question: 'What\'s involved in a septic inspection?', answer: 'Tank levels, pipe condition, drain field health, and a check of baffles and filters.' },
      { question: 'Can heavy rain affect my septic system?', answer: 'Yes. Saturated drain fields can\'t filter wastewater as effectively. Good system design helps minimize this.' },
    ],
    relatedServices: ['sewer-line', 'new-construction'],
  },
  {
    slug: 'remodels',
    title: 'Plumbing Remodels & Upgrades',
    description: 'Update your plumbing with energy-efficient fixtures and modern piping. We work with your vision and budget to deliver upgrades that last.',
    image: '/images/service-kitchen-remodel-plumbing.webp',
    features: ['Kitchen plumbing remodel', 'Bathroom plumbing remodel', 'Fixture upgrades', 'Piping relocation', 'Code-compliance updates', 'Energy-efficient upgrades'],
    faqs: [
      { question: 'How long does a kitchen or bathroom plumbing remodel take?', answer: 'Most take 2 to 5 days. A simple swap may be one day. Full renovations can take up to a week.' },
      { question: 'Do I need permits for a plumbing remodel?', answer: 'Yes. We handle all permits and inspections so your remodel passes code without hassle.' },
      { question: 'Can you relocate plumbing during a remodel?', answer: 'Yes. We move supply lines, drain pipes, and vents for new layouts. Everything meets code in its new position.' },
      { question: 'What plumbing upgrades add the most value?', answer: 'Tankless water heaters, low-flow fixtures, touchless faucets, and radiant floor heating. They improve efficiency and appeal.' },
      { question: 'Do you work with my contractor or designer?', answer: 'Yes. We work alongside contractors, designers, and architects to keep the project on track.' },
      { question: 'Can you match existing fixtures during a partial remodel?', answer: 'Yes. We find fixtures that match your brand and style. If exact matches aren\'t available, we suggest close alternatives.' },
      { question: 'Do you offer warranties on remodel work?', answer: 'Yes. Warranties on materials and labor are included and outlined in your estimate.' },
      { question: 'How much does a plumbing remodel typically cost?', answer: 'Costs vary by scope and materials. We give free, detailed estimates before any work starts.' },
    ],
    relatedServices: ['bathtubs-showers', 'toilets-faucets', 'dishwashers'],
  },
  {
    slug: 'kitchen-remodels',
    title: 'Kitchen Remodels',
    description: 'New plumbing layouts, appliance hookups, and water-efficient fixtures for your kitchen. We work with your remodel plans for a setup that functions well and lasts.',
    image: '/images/service-kitchen-remodel-plumbing.webp',
    features: ['Sink installation and relocation', 'Dishwasher hookup', 'Garbage disposal installation', 'Refrigerator water line', 'Pot filler installation', 'Island plumbing', 'Water-efficient fixtures'],
    faqs: [
      { question: 'How long does a kitchen plumbing remodel take?', answer: 'Most take 2 to 5 days. A simple swap may be one day. Full remodels with gas line work can take up to a week.' },
      { question: 'Can you move my sink to a new location?', answer: 'Yes. We reconfigure supply and drain lines for your new layout. Proper slope, venting, and code are part of the job.' },
      { question: 'Do you install pot fillers and instant hot water dispensers?', answer: 'Yes. We install pot fillers over the stove and instant hot dispensers at the sink with proper shutoff valves.' },
      { question: 'What plumbing should I plan for a kitchen island?', answer: 'Islands with sinks or dishwashers need supply and drain lines under the floor. We coordinate with your contractor to run them before the subfloor is finished.' },
      { question: 'Can you install a farmhouse or apron sink?', answer: 'Yes. We install farmhouse, undermount, and apron sinks with watertight drain connections.' },
      { question: 'Do I need a permit for kitchen plumbing work?', answer: 'Most kitchen plumbing modifications require permits. We handle all permitting and coordinate with inspectors.' },
      { question: 'What type of kitchen faucet is best for hard water?', answer: 'Touchless or pull-down faucets with ceramic disc valves hold up best. A water softener helps even more.' },
      { question: 'Can you install gas lines for a gas range?', answer: 'Yes. Our licensed technicians install gas lines for ranges and cooktops. We pressure-test every connection.' },
    ],
    relatedServices: ['remodels', 'dishwashers', 'toilets-faucets'],
  },
  {
    slug: 'bathroom-remodels',
    title: 'Bathroom Remodels',
    description: 'New fixtures or total re-piping. We handle showers, tubs, vanities, toilets, and custom plumbing features. We build bathrooms that work and look good.',
    image: '/images/service-bathtubs-showers-plumbing.webp',
    features: ['Vanity and sink installation', 'Shower and tub plumbing', 'Toilet installation', 'Re-piping and rerouting', 'Radiant floor heat', 'ADA-compliant upgrades', 'Custom shower systems'],
    faqs: [
      { question: 'How long does a full bathroom plumbing remodel take?', answer: 'Most take 3 to 7 days. Simple updates may be 1 to 2 days. Complete re-piping can take up to a week.' },
      { question: 'Can you convert a tub to a walk-in shower?', answer: 'Yes. We cap existing supply lines, install a new shower valve and drain, and prep for tiling.' },
      { question: 'Do you install heated bathroom floors?', answer: 'Yes. Electric and hydronic radiant floor heating. Adds warmth and efficiency, especially in Idaho winters.' },
      { question: 'Can you relocate a toilet or vanity in a bathroom remodel?', answer: 'Yes. We move them by reconfiguring waste, vent, and supply lines. Everything meets code.' },
      { question: 'What plumbing upgrades add the most value to a bathroom?', answer: 'Walk-in showers, dual-flush toilets, touchless faucets, heated floors, and soaking tubs.' },
      { question: 'Do I need permits for a bathroom remodel?', answer: 'Yes. We handle all permits and inspections to keep your remodel code-compliant.' },
      { question: 'Can you install a curbless or zero-entry shower?', answer: 'Yes. With proper slope and waterproofing. Great for accessibility and a modern look.' },
      { question: 'Do you work with my contractor or designer on bathroom remodels?', answer: 'Yes. We coordinate with contractors, designers, and architects so the plumbing fits the design.' },
    ],
    relatedServices: ['remodels', 'bathtubs-showers', 'toilets-faucets'],
  },
  {
    slug: 'emergency',
    title: 'Emergency Plumbing (24/7)',
    description: 'Fast emergency plumbing to stop damage and get your system back online. Available 24/7 for urgent plumbing needs across the region.',
    image: '/images/service-emergency-plumbing-repair.webp',
    features: ['24/7 emergency service', 'Burst pipe repair', 'Water damage mitigation', 'Sewer backup cleanup', 'Gas leak detection', 'No-hot-water emergencies'],
    faqs: [
      { question: 'How quickly can you respond to a plumbing emergency?', answer: 'We aim to arrive within the hour for urgent calls in the Spirit Lake area. Our trucks are stocked for most emergencies.' },
      { question: 'What constitutes a plumbing emergency?', answer: 'Burst pipes, gas leaks, sewage backups, no hot water, overflowing toilets, and major leaks. Call us right away.' },
      { question: 'Do you charge extra for emergency calls?', answer: 'Emergency rates are higher than standard appointments. We give you the price upfront before any work starts.' },
      { question: 'Can you handle emergency gas line repairs?', answer: 'Yes. Our licensed techs are trained in gas line shutdown and repair. If you smell gas, leave the area and call us.' },
      { question: 'What should I do while waiting for the emergency plumber?', answer: 'Shut off the main water valve if you can. Move valuables away from the area. Our dispatch team can walk you through it.' },
      { question: 'Do you offer emergency services on weekends and holidays?', answer: 'Yes. 24/7, 365 days a year. Plumbing problems don\'t take days off.' },
      { question: 'How do I shut off my water in an emergency?', answer: 'The main valve is near your water meter, in the basement, or where the main line enters your home. Call us if you can\'t find it.' },
      { question: 'Will emergency plumbing service cost more than regular service?', answer: 'Yes, due to the immediate response. We always give an estimate before starting work.' },
    ],
    relatedServices: ['sewer-line', 'water-heaters'],
  },
]

export const areas: AreaPage[] = [
  { city: 'Spirit Lake', state: 'ID', slug: 'spirit-lake-id', fullName: 'Spirit Lake, Idaho', description: 'We are based here. Spirit Lake homes and businesses know us for showing up and doing the job right.', latitude: 47.9668, longitude: -116.8693 },
  { city: "Coeur d'Alene", state: 'ID', slug: 'coeur-dalene-id', fullName: "Coeur d'Alene, Idaho", description: 'Plumbing for Coeur d\'Alene homes and businesses. From new construction to emergency repairs, we cover the whole area.', latitude: 47.6777, longitude: -116.7805 },
  { city: 'Post Falls', state: 'ID', slug: 'post-falls-id', fullName: 'Post Falls, Idaho', description: 'Full plumbing services for Post Falls. New builds, remodels, water heaters, and 24/7 emergency calls.', latitude: 47.7180, longitude: -116.9516 },
  { city: 'Sandpoint', state: 'ID', slug: 'sandpoint-id', fullName: 'Sandpoint, Idaho', description: 'Serving Sandpoint and Bonner County with reliable plumbing. We handle everything from radiant heat to sewer lines.', latitude: 48.2766, longitude: -116.5535 },
  { city: 'Hayden', state: 'ID', slug: 'hayden-id', fullName: 'Hayden, Idaho', description: 'Hayden homeowners and businesses count on us for quality plumbing work. Repairs, remodels, new construction.', latitude: 47.7660, longitude: -116.7866 },
  { city: 'Rathdrum', state: 'ID', slug: 'rathdrum-id', fullName: 'Rathdrum, Idaho', description: 'Plumbing contractor for Rathdrum and the surrounding area. Residential and commercial, big or small.', latitude: 47.8105, longitude: -116.8966 },
  { city: 'Moscow', state: 'ID', slug: 'moscow-id', fullName: 'Moscow, Idaho', description: 'Plumbing services in Moscow. We travel to serve the Palouse region with the same quality work we do at home.', latitude: 46.7324, longitude: -117.0002 },
  { city: 'Bellevue', state: 'ID', slug: 'bellevue-id', fullName: 'Bellevue, Idaho', description: 'Plumbing work in Bellevue and the Wood River Valley. New construction, remodels, and emergency service.', latitude: 43.4634, longitude: -114.2604 },
  { city: 'Priest River', state: 'ID', slug: 'priest-river-id', fullName: 'Priest River, Idaho', description: 'Plumbing contractor for Priest River and Bonner County. We keep homes and businesses running year-round.', latitude: 48.1810, longitude: -116.9100 },
  { city: 'Athol', state: 'ID', slug: 'athol-id', fullName: 'Athol, Idaho', description: 'Plumbing services in Athol and Kootenai County. Right down the road from Spirit Lake, we get there fast.', latitude: 47.9477, longitude: -116.7080 },
  { city: 'Blanchard', state: 'ID', slug: 'blanchard-id', fullName: 'Blanchard, Idaho', description: 'Plumbing for Blanchard and North Idaho. New construction, well systems, and everything in between.', latitude: 48.0169, longitude: -116.9833 },
  { city: 'Clark Fork', state: 'ID', slug: 'clark-fork-id', fullName: 'Clark Fork, Idaho', description: 'Plumbing serving Clark Fork and Bonner County. We handle repairs, new builds, and emergencies.', latitude: 48.1470, longitude: -116.6390 },
  { city: 'Newport', state: 'WA', slug: 'newport-wa', fullName: 'Newport, Washington', description: 'Plumbing contractor for Newport and Pend Oreille County. We cross the border for the same quality work.', latitude: 48.1794, longitude: -117.0430 },
  { city: 'Mead', state: 'WA', slug: 'mead-wa', fullName: 'Mead, Washington', description: 'Plumbing services in Mead and Spokane County. Residential, commercial, and emergency service available.', latitude: 47.7674, longitude: -117.3544 },
  { city: 'Chattaroy', state: 'WA', slug: 'chattaroy-wa', fullName: 'Chattaroy, Washington', description: 'Plumbing in Chattaroy and Spokane County. We serve rural and residential properties with the same standards.', latitude: 47.8935, longitude: -117.3538 },
  { city: 'Oldtown', state: 'ID', slug: 'oldtown-id', fullName: 'Oldtown, Idaho', description: 'Plumbing solutions for Oldtown and the surrounding area. Right on the border, close to Spirit Lake.', latitude: 48.1857, longitude: -117.0296 },
]

export const reviews: Review[] = [
  { id: '1', name: 'Mike R.', location: 'Spirit Lake, ID', rating: 5, text: 'Pipe was spraying water under the kitchen sink at 7pm. They showed up within the hour, fixed it, and didn\'t upsell me on anything. That\'s rare these days.', date: '2025-11-01' },
  { id: '2', name: 'Shannon W.', location: 'Hayden, ID', rating: 5, text: 'Had a new water heater put in. They walked me through the options, gave me a straight price, and had it running before dinner. No complaints at all.', date: '2025-10-15' },
  { id: '3', name: 'Tom K.', location: 'Post Falls, ID', rating: 5, text: 'Main drain was backed up bad. Called in the morning, they were here by noon. Cleared it out and showed me what caused it so I can avoid it next time.', date: '2025-09-22' },
  { id: '4', name: 'Lukas A.', location: 'Rathdrum, ID', rating: 5, text: 'Replaced our old toilet and fixed a slow leak under the sink while they were at it. Solid work, fair price. Would recommend.', date: '2025-08-05' },
  { id: '5', name: 'Rachel M.', location: 'Coeur d\'Alene, ID', rating: 5, text: 'Had radiant heat put in the basement last fall. Best decision we made. Room stays comfortable all winter and the install was clean and on time.', date: '2025-07-15' },
]

export const faqItems = [
  { question: 'Do you offer emergency plumbing services in Spirit Lake?', answer: 'Yes, we offer 24/7 emergency plumbing throughout Spirit Lake and the surrounding areas.' },
  { question: 'How soon can you start a new construction plumbing project?', answer: 'We can usually start within a week or two after the plans and permits are done.' },
  { question: 'Are your plumbers licensed and insured?', answer: 'Absolutely. Every one of our technicians is fully licensed, insured, and background checked.' },
  { question: 'What\'s included in a plumbing remodel?', answer: 'We swap out old plumbing, put in new fixtures, move things around as needed, and make sure everything is up to code.' },
  { question: 'Do you install energy-efficient radiant floor heating?', answer: 'Yes, we specialize in radiant in-floor systems for new builds and remodels.' },
  { question: 'Can I get an estimate before scheduling service?', answer: 'Of course. We give free estimates with no strings attached.' },
  { question: 'Do you work with general contractors on construction projects?', answer: 'Yes, we work alongside builders, architects, and general contractors all the time.' },
  { question: 'What areas besides Spirit Lake do you serve?', answer: 'We cover Spirit Lake and 15 other communities across northern Idaho and eastern Washington.' },
]
